package com.alsb.security.lib;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Thu Dec 20 14:02:17 PST 2007  
 */

public interface SecureMessageService_Service extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: SecureMessageServiceSOAP  
     // Port Type: SecureMessageService_PortType   
     //***********************************
     
  /**
   * returns SecureMessageServiceSOAP port in this service 
   */
  com.alsb.security.lib.SecureMessageService_PortType getSecureMessageServiceSOAP() throws javax.xml.rpc.ServiceException;

  /**
   * @deprecated Use getSecureMessageServiceSOAP(byte[] username, byte[] password);
   */
  com.alsb.security.lib.SecureMessageService_PortType getSecureMessageServiceSOAP(String username, String password) throws javax.xml.rpc.ServiceException;

  com.alsb.security.lib.SecureMessageService_PortType getSecureMessageServiceSOAP(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
    
  }