package com.alsb.security.lib;

/**
 * Generated interface, do not edit.
 *
 * This stub interface was generated by weblogic
 * webservice stub gen on Thu Dec 20 14:02:17 PST 2007  
 */

public interface SecureMessageService_PortType extends java.rmi.Remote {
     
  /**
   * Operation Name : {http://www.alsb.com/SecureMessageService/}getAccount   */

  public com.alsb.securemessageservice.GetAccountResponse getAccount(com.alsb.securemessageservice.GetAccount parameters) throws java.rmi.RemoteException;
    public void getAccountAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.alsb.securemessageservice.GetAccount parameters) throws java.rmi.RemoteException ;
  
}