package com.alsb.security.lib;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Thu Dec 20 14:02:17 PST 2007 */

public class SecureMessageService_Service_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements com.alsb.security.lib.SecureMessageService_Service {

  public SecureMessageService_Service_Impl() throws javax.xml.rpc.ServiceException {
    this("com/alsb/security/lib/SecureMessageService_Service_saved_wsdl.wsdl", null);
  }
  
  public SecureMessageService_Service_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public SecureMessageService_Service_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://www.alsb.com/SecureMessageService/", "SecureMessageService"),
          "com/alsb/security/lib/SecureMessageService_Service_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: SecureMessageServiceSOAP 
  // Port Type: SecureMessageService_PortType 
  //***********************************

  com.alsb.security.lib.SecureMessageService_PortType mvar_SecureMessageServiceSOAP;

  /**
   * returns SecureMessageServiceSOAP port in this service 
   */
  public com.alsb.security.lib.SecureMessageService_PortType getSecureMessageServiceSOAP() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_SecureMessageServiceSOAP == null) {
      mvar_SecureMessageServiceSOAP =
        new com.alsb.security.lib.SecureMessageService_PortType_Stub(_getPort("SecureMessageServiceSOAP"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_SecureMessageServiceSOAP)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_SecureMessageServiceSOAP;
  }

  /**
   * @deprecated  Use getSecureMessageServiceSOAP(byte[] username, byte[] password)
   */
  public com.alsb.security.lib.SecureMessageService_PortType getSecureMessageServiceSOAP(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getSecureMessageServiceSOAP();
  }

  public com.alsb.security.lib.SecureMessageService_PortType getSecureMessageServiceSOAP(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getSecureMessageServiceSOAP();
  }
  
  
}