package com.alsb.security.lib;

/**
 * Generated class, do not edit.
 *
 * This stub class was generated by weblogic
 * webservice stub gen on Thu Dec 20 14:02:17 PST 2007 
 */

public class SecureMessageService_PortType_Stub 
     extends weblogic.wsee.jaxrpc.StubImpl
     implements com.alsb.security.lib.SecureMessageService_PortType, /**/java.io.Serializable
{

  public SecureMessageService_PortType_Stub(weblogic.wsee.wsdl.WsdlPort port, 
                        weblogic.wsee.jaxrpc.ServiceImpl service) 
    throws javax.xml.rpc.ServiceException
  {
    super(port, com.alsb.security.lib.SecureMessageService_PortType.class, service);
  }
  
    
  /**
   * Operation Name : {http://www.alsb.com/SecureMessageService/}getAccount   */

  public com.alsb.securemessageservice.GetAccountResponse getAccount(com.alsb.securemessageservice.GetAccount parameters) throws java.rmi.RemoteException {

    java.util.ArrayList _args = new java.util.ArrayList();
    _args.add(parameters);
    
    try {
            java.lang.Object _result = _invoke("getAccount", _args.toArray());
      return (com.alsb.securemessageservice.GetAccountResponse)_result;
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {

      
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
  }  public void getAccountAsync(weblogic.wsee.async.AsyncPreCallContext apc, com.alsb.securemessageservice.GetAccount parameters) throws java.rmi.RemoteException  {
    java.util.ArrayList _args = new java.util.ArrayList();

    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY, "true");
    _setProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY, apc);
    _setProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY, "getAccount");
    _setProperty(weblogic.wsee.async.AsyncConstants.OPERATION_NAME_PROPERTY,
                 "getAccount");
    _setProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY, "com.alsb.securemessageservice.GetAccountResponse");
    _args.add(parameters);
    
    try {
      java.lang.Object _result = _invoke("getAccount", _args.toArray());
    } catch (javax.xml.rpc.JAXRPCException _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception.getLinkedCause());
    } catch (javax.xml.rpc.soap.SOAPFaultException _wls_exception) {
      throw new java.rmi.RemoteException(_soapFault2String(_wls_exception), _wls_exception);
    } catch (java.lang.Throwable _wls_exception) {
      throw new java.rmi.RemoteException(_wls_exception.getMessage(), _wls_exception);
    }
    finally {
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_INVOKE_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.ASYNC_PRE_CALL_CONTEXT_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.METHOD_NAME_PROPERTY);
      _removeProperty(weblogic.wsee.async.AsyncConstants.RETURN_TYPE_PROPERTY);

    }
  }
   
    
  private Object writeReplace() throws java.io.ObjectStreamException {
    java.util.HashMap map = new java.util.HashMap();
            map.put("SecureMessageServiceSOAP", "SecureMessageServiceSOAP");
            
    return new weblogic.wsee.tools.clientgen.stubgen.StubSerialWrapper(
      "com.alsb.security.lib.SecureMessageService_Service",
      (String)map.get(_getPortName()),
      _getUserProperties());
  }
}