package com.alsb.security.lib;

/**
 * Generated class, do not edit.
 *
 * This service interface was generated by weblogic
 * webservice stub gen on Thu Dec 20 14:02:18 PST 2007  
 */

public interface UnsecureMessageService_Service extends javax.xml.rpc.Service {

  weblogic.wsee.context.WebServiceContext context();

  weblogic.wsee.context.WebServiceContext joinContext()
       throws weblogic.wsee.context.ContextNotFoundException;
 
     

     //***********************************
     // Port Name: UnsecureMessageServiceSOAP  
     // Port Type: UnsecureMessageService_PortType   
     //***********************************
     
  /**
   * returns UnsecureMessageServiceSOAP port in this service 
   */
  com.alsb.security.lib.UnsecureMessageService_PortType getUnsecureMessageServiceSOAP() throws javax.xml.rpc.ServiceException;

  /**
   * @deprecated Use getUnsecureMessageServiceSOAP(byte[] username, byte[] password);
   */
  com.alsb.security.lib.UnsecureMessageService_PortType getUnsecureMessageServiceSOAP(String username, String password) throws javax.xml.rpc.ServiceException;

  com.alsb.security.lib.UnsecureMessageService_PortType getUnsecureMessageServiceSOAP(byte[] username, byte[] password) throws javax.xml.rpc.ServiceException;
  
    
  }