package com.alsb.security.lib;

/**
 * Generated class, do not edit.
 *
 * This service class was generated by weblogic
 * webservice stub gen on Thu Dec 20 14:02:18 PST 2007 */

public class UnsecureMessageService_Service_Impl     extends weblogic.wsee.jaxrpc.ServiceImpl
     implements com.alsb.security.lib.UnsecureMessageService_Service {

  public UnsecureMessageService_Service_Impl() throws javax.xml.rpc.ServiceException {
    this("com/alsb/security/lib/UnsecureMessageService_Service_saved_wsdl.wsdl", null);
  }
  
  public UnsecureMessageService_Service_Impl(String wsdlurl) throws javax.xml.rpc.ServiceException {
    this(wsdlurl, null);
  }
  
  public UnsecureMessageService_Service_Impl(String wsdlurl, weblogic.wsee.connection.transport.TransportInfo transportInfo) throws javax.xml.rpc.ServiceException {
    super(wsdlurl,
          new javax.xml.namespace.QName("http://www.alsb.com/SecureMessageService/", "UnsecureMessageService"),
          "com/alsb/security/lib/UnsecureMessageService_Service_internaldd.xml", transportInfo);
  }
  
  //***********************************
  // Port Name: UnsecureMessageServiceSOAP 
  // Port Type: UnsecureMessageService_PortType 
  //***********************************

  com.alsb.security.lib.UnsecureMessageService_PortType mvar_UnsecureMessageServiceSOAP;

  /**
   * returns UnsecureMessageServiceSOAP port in this service 
   */
  public com.alsb.security.lib.UnsecureMessageService_PortType getUnsecureMessageServiceSOAP() 
    throws javax.xml.rpc.ServiceException
  {

    if (mvar_UnsecureMessageServiceSOAP == null) {
      mvar_UnsecureMessageServiceSOAP =
        new com.alsb.security.lib.UnsecureMessageService_PortType_Stub(_getPort("UnsecureMessageServiceSOAP"), this);
    }

    if (transportInfo != null && 
        transportInfo instanceof weblogic.wsee.connection.transport.http.HttpTransportInfo) {
      ((javax.xml.rpc.Stub)mvar_UnsecureMessageServiceSOAP)._setProperty(
        "weblogic.wsee.connection.transportinfo", 
        (weblogic.wsee.connection.transport.http.HttpTransportInfo)transportInfo);
    }
    
    return mvar_UnsecureMessageServiceSOAP;
  }

  /**
   * @deprecated  Use getUnsecureMessageServiceSOAP(byte[] username, byte[] password)
   */
  public com.alsb.security.lib.UnsecureMessageService_PortType getUnsecureMessageServiceSOAP(String username, String password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username.getBytes());
      httpInfo.setPassword(password.getBytes());
      transportInfo = httpInfo;
    }
    return getUnsecureMessageServiceSOAP();
  }

  public com.alsb.security.lib.UnsecureMessageService_PortType getUnsecureMessageServiceSOAP(byte[] username, byte[] password) 
    throws javax.xml.rpc.ServiceException
  {
    if (username != null & password != null) {
      weblogic.wsee.connection.transport.http.HttpTransportInfo httpInfo = 
        new weblogic.wsee.connection.transport.http.HttpTransportInfo();
      httpInfo.setUsername(username);
      httpInfo.setPassword(password);
      transportInfo = httpInfo;
    }
    return getUnsecureMessageServiceSOAP();
  }
  
  
}