package com.alsb.ejb;


/*
  ** This file was automatically generated by 
  ** EJBGen WebLogic Server 10.3 SP0  Fri Jul 25 16:30:05 EDT 2008 1137967 
*/


import javax.ejb.CreateException;
import javax.ejb.EJBHome;
import javax.ejb.FinderException;
import java.rmi.RemoteException;
import java.util.Collection;

// BEGIN imports from bean class
import javax.ejb.SessionBean;
import weblogic.ejb.GenericSessionBean;
import weblogic.ejbgen.Constants;
import weblogic.ejbgen.FileGeneration;
import weblogic.ejbgen.JndiName;
import weblogic.ejbgen.RemoteMethod;
import weblogic.ejbgen.Session;
// END imports from bean class


/**
 * * 
 * GenericSessionBean subclass automatically generated by Workshop.
 * Please complete the ejbCreate method as needed to properly initialize new instances of your bean and add
 * all required business methods. Also, review the Session, JndiName and FileGeneration annotations 
 * to ensure the settings match the bean's intended use.
 
 */

public interface TaxCalculatorRemoteHome extends EJBHome {



  public TaxCalculatorRemote create()     throws CreateException, RemoteException, javax.ejb.CreateException;



}
